services:
  - type: web
    name: Rairu-Kun2
    env: docker
    repo: https://github.com/clickmamaheti-prog/rairu-kun2
    region: singapore
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8080
      - key: ZROK_TOKEN
        sync: false
      - key: ROOT_PASS
        sync: false
      - key: NTFY_TOPIC
        value: zrokIP22
      - key: TZ
        value: Asia/Jakarta
